import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Script from "next/script";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased `} >
        <Script src="https://cdn.lordicon.com/lordicon.js" strategy="afterInteractive" />
        <div className="font-mono">
        <Navbar/>
        {children}
        <div className="fixed bottom-0 w-full">

        <Footer/>
        </div>
        </div>
      </body>
    </html>
  );
}
